name: Synergy
main: usa.devrocoding.synergy.spigot.Core
description: Dynamic Backend System
version: 1.0
api-version: 1.13
author: JusJus

#We are softdepending Multiverse, because we always need to load the worlds before everything!
softdepend: [PlaceHolderAPI, Multiverse-Core]