name: Synergy
main: usa.devrocoding.synergy.spigot.Core
description: Dynamic Backend System
version: 1.0
api-version: 1.13
author: JusJus

depend: [PacketWrapper, ProtocolLib]

#We are softdepending WorldManagers, because we always need to load the worlds before enabling Synergy!
softdepend: [WorldEdit, PlaceHolderAPI, Essentials, Vault, Multiverse-Core, PlotSquared, PlotMe, MultiWorld]